backend:
  name: git-gateway
  branch: main
local_backend: true

media_folder: "static/uploads/gallery"
public_folder: "/uploads/gallery"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/en/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: "md"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime", format: YYYY-MM-DD }
      - { label: "Image", name: "image", widget: "image", required: true }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Body", name: "body", widget: "markdown" }    
